services:
    db:
        image: postgres:latest
        ports:
            - 5432:5432
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            POSTGRES_DB: live_view_with_js_dev
        volumes:
            - live_view_with_js_dev-data:/var/lib/postgresql/data/
volumes:
    live_view_with_js_dev-data:
